# Generated by Django 5.1.4 on 2025-02-24 18:20

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('New', 'New'), ('Men', 'Men'), ('Women', 'Women'), ('Accessories', 'Accessories'), ('Collections', 'Collections'), ('Store', 'Store'), ('Bags & Leather Goods', 'Bags & Leather Goods')], max_length=40)),
                ('status', models.CharField(choices=[('available', 'available'), ('out', 'out')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='content/')),
                ('image_2', models.FileField(blank=True, upload_to='content/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField(max_length=10000)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vidoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_1', models.FileField(blank=True, upload_to='content/')),
                ('vdeo_2', models.FileField(blank=True, upload_to='content/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog_videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='blog_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='michan_styles.blogpost')),
            ],
        ),
    ]
